[package]
name = "shelly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_util = "0.1.2"
thiserror = "1.0.47"
zerocopy = { version = "0.7.5", features = ["derive"] }
